--DROP TABLE SAL.DIM_GEN_PERIODS CASCADE CONSTRAINTS;

CREATE TABLE SAL.DIM_GEN_PERIODS
(
  PERIOD_SURR_ID        NUMBER        PRIMARY KEY,
  PERIOD_ID             NUMBER        NOT NULL, 
  PERIOD_CODE           VARCHAR2(30)  NOT NULL,
  PERIOD_DESC           VARCHAR2(50)  NOT NULL,
  VALUE_FROM_NUM        NUMBER        NOT NULL,
  VALUE_TO_NUM          NUMBER        NOT NULL,
  VALUE_FROM_DT         DATE          NOT NULL,
  VALUE_TO_DT           DATE          NOT NULL,
  VALUE_FROM_CHAR       VARCHAR2(20)  NOT NULL,
  VALUE_TO_CHAR         VARCHAR2(20)  NOT NULL,
  LEVEL_CODE            VARCHAR2(20)  NOT NULL,
  INSERT_DT             DATE          NOT NULL,
  UPDATE_DT             DATE          NOT NULL
)
TABLESPACE TS_SAL_DATA_01
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );