--DROP TABLE SAL.DIM_COUNTRIES_SCD CASCADE CONSTRAINTS;

CREATE TABLE SAL.DIM_COUNTRIES_SCD
(
  COUNTRY_SURR_ID       NUMBER        PRIMARY KEY,
  COUNTRY_ID            NUMBER        NOT NULL,
  COUNTRY_CODE_A2       VARCHAR2(30)  NOT NULL,
  COUNTRY_CODE_A3       VARCHAR2(30)  NOT NULL,
  COUNTRY_DESC          VARCHAR2(200) NOT NULL,
  REGION_ID             NUMBER        NOT NULL,
  REGION_CODE           VARCHAR2(30)  NOT NULL,
  REGION_DESC           VARCHAR2(200) NOT NULL,
  PART_ID               NUMBER        NOT NULL,
  PART_CODE             VARCHAR2(30)  NOT NULL,
  PART_DESC             VARCHAR2(200) NOT NULL,
  GEO_SYSTEM_ID         NUMBER        NOT NULL,
  GEO_SYSTEM_CODE       VARCHAR2(30)  NOT NULL,
  GEO_SYSTEM_DESC       VARCHAR2(200) NOT NULL,
  SUBGROUP_ID           NUMBER        NOT NULL,
  SUBGROUP_CODE         VARCHAR2(30)  NOT NULL,
  SUBGROUP_DESC         VARCHAR2(200) NOT NULL,
  GROUP_ID              NUMBER        NOT NULL,
  GROUP_CODE            VARCHAR2(30)  NOT NULL,
  GROUP_DESC            VARCHAR2(200) NOT NULL,
  GRP_SYSTEM_ID         NUMBER        NOT NULL,
  GRP_SYSTEM_CODE       VARCHAR2(30)  NOT NULL,
  GRP_SYSTEM_DESC       VARCHAR2(200) NOT NULL,
  LEVEL_CODE            VARCHAR2(20)  NOT NULL,
  VALID_FROM            DATE          NOT NULL,
  VALID_TO              DATE          NOT NULL,
  IS_ACTIVE             VARCHAR2(4)   NOT NULL,
  INSERT_DT             DATE          NOT NULL
)
TABLESPACE TS_SAL_DATA_01
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );