SELECT DISTINCT
    ( CASE
      WHEN TO_CHAR( SD + RN, 'D' ) IN ( 1, 2, 3, 4, 5, 6 ) THEN
        NEXT_DAY( SD + RN, 'SATURDAY' )
      ELSE
        ( SD + RN )
    END ) -6 WEEK_ID,   
TRUNC(( SD + RN ), 'YYYY') YEAR_ID,
  ( CASE
      WHEN TO_CHAR( SD + RN, 'D' ) IN ( 1, 2, 3, 4, 5, 6 ) THEN
        NEXT_DAY( SD + RN, 'SATURDAY' )
      ELSE
        ( SD + RN )
    END ) WEEK_ENDING_DATE
  FROM
  ( 
    SELECT 
      TO_DATE( '12/31/2012', 'MM/DD/YYYY' ) SD, ROWNUM AS RN
    FROM DUAL
      CONNECT BY LEVEL <= 365
  )
  ORDER BY 1));
  
ALTER TABLE T_WEEKS
ADD CONSTRAINT TW_PK PRIMARY KEY (WEEK_ID);

ALTER TABLE T_WEEKS
ADD CONSTRAINT TW_FK1 FOREIGN KEY (YEAR_ID) REFERENCES T_YEARS (YEAR_ID);
